---
- name: Metricbeat
  hosts: webservers
  become: yes
  tasks:
    - name: download
      shell:
        cmd: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.6.1-amd64.deb
        warn: false

    - name: install
      shell:
        cmd: dpkg -i metricbeat-7.6.1-amd64.deb

    - name: override config
      copy:
        src: metricbeat-configuration.yml
        dest: /etc/metricbeat/metricbeat.yml

    - name: run
      shell:
        cmd: metricbeat modules enable docker && metricbeat setup && metricbeat -e &
